#%RAML 1.0
title: uhub-sapi
version: v1
baseUri: https://{environment}/covid/{version}/
baseUriParameters:
  environment:
    description: DEV,TEST,UAT,PROD
    enum: ["uho-dev-uhub-sapi.us-e2.cloudhub.io","uho-test-uhub-sapi.us-e2.cloudhub.io", "uho-uat-uhub-sapi.us-e2.cloudhub.io", "uho-prod-uhub-sapi.us-e2.cloudhub.io"]
traits:
  client-id-required: !include /traits/client-id-required.raml
  correlation-id-header: !include /traits/correlation-id-header.raml
  state-query-param: !include /traits/state-query-param.raml
  transaction-header: !include /traits/transaction-header.raml

uses:
  common-Data-types: /dataType/common-data-types.raml
  uhub-sapi-types: /dataType/uhub-sapi-type.raml
  resourceType: /resource-type/resourceType.raml
/cases:
  post:
    is: [client-id-required,correlation-id-header,transaction-header]
    body:
      application/json:
        type: uhub-sapi-types.covid-case-request
        example:
          !include /example/Body-example/covid-case-request.json
    responses:
      201:
        body:
          application/json:
            type: uhub-sapi-types.covid-case-response-type
            example:
              !include /example/Responses/201.json
      503:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/503.json
      400:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/400.json
      500:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/500.json
  put:
    is: [client-id-required,correlation-id-header,transaction-header]
    body:
      application/json:
        type: uhub-sapi-types.covid-case-request
        example:
          !include /example/Body-example/case-put-body.json
    responses:
      200:
        body:
          application/json:
            example:
              !include /example/Responses/200.json
      503:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/503.json
      400:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/400.json
      500:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/500.json
  /{nationalId}:
    get:
      is: [client-id-required,correlation-id-header,transaction-header]
      responses:
        200:
          body:
            application/json:
              type: uhub-sapi-types.get-cases-by-national-id-response-type
              example:
                !include /example/Body-example/get-cases-by-national-id-response.json
        404:
          body:
            application/json:
              type: common-Data-types.errorType
              example:
                !include /example/Responses/404.json
        503:
          body:
            application/json:
              type: common-Data-types.errorType
              example:
                !include /example/Responses/503.json
        500:
          body:
            application/json:
              type: common-Data-types.errorType
              example:
                !include /example/Responses/500.json
/reports:
  get:
    is: [client-id-required,correlation-id-header,transaction-header,state-query-param]
    responses:
      200:
        body:
          application/json:
            type: uhub-sapi-types.get-reports-response-type
            example:
              !include /example/Body-example/get-reports-response.json
      503:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/503.json
      500:
        body:
          application/json:
            type: common-Data-types.errorType
            example:
              !include /example/Responses/500.json
/health-check:
  get:
  type:
    resourceType.all: 
      getResponseType: string
